/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BatchMetadataItemType } from './batch-metadata-item-type';

/**
 * 
 * @export
 * @interface BatchMetadataItem
 */
export interface BatchMetadataItem {
    /**
     * 
     * @type {number}
     * @memberof BatchMetadataItem
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof BatchMetadataItem
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchMetadataItem
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof BatchMetadataItem
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BatchMetadataItem
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BatchMetadataItem
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BatchMetadataItem
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof BatchMetadataItem
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof BatchMetadataItem
     */
    batchMetadataId?: number;
    /**
     * 
     * @type {string}
     * @memberof BatchMetadataItem
     */
    name?: string | null;
    /**
     * 
     * @type {BatchMetadataItemType}
     * @memberof BatchMetadataItem
     */
    type?: BatchMetadataItemType;
}


