/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BatchStatus } from './batch-status';
import { EnvironmentData } from './environment-data';

/**
 * 
 * @export
 * @interface Batch
 */
export interface Batch {
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Batch
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Batch
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof Batch
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    productionId?: number;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    quantityInKgs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    harvestDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    quantityInCrates?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    batchId?: number;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    facilityId?: number | null;
    /**
     * 
     * @type {BatchStatus}
     * @memberof Batch
     */
    status?: BatchStatus;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    supplierId?: number;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    templateId?: number;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    commercialProductName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    procurementDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    shippingDate?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    distributorId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    destinationCustomerId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    interfaceCustomerId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    approvalDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    arrivalDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Batch
     */
    customerId?: number | null;
    /**
     * 
     * @type {Array<EnvironmentData>}
     * @memberof Batch
     */
    environmentData?: Array<EnvironmentData> | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    packagingDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Batch
     */
    expirationDate?: string | null;
}


