/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BatchMetadataItemType } from './batch-metadata-item-type';

/**
 * 
 * @export
 * @interface BatchDataItemModel
 */
export interface BatchDataItemModel {
    /**
     * 
     * @type {string}
     * @memberof BatchDataItemModel
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BatchDataItemModel
     */
    value?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BatchDataItemModel
     */
    batchMetadataItemUid?: string;
    /**
     * 
     * @type {BatchMetadataItemType}
     * @memberof BatchDataItemModel
     */
    itemType?: BatchMetadataItemType;
    /**
     * 
     * @type {string}
     * @memberof BatchDataItemModel
     */
    placeholder?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BatchDataItemModel
     */
    tag?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BatchDataItemModel
     */
    code?: string | null;
}


