/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyCertificate
 */
export interface CompanyCertificate {
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyCertificate
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyCertificate
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof CompanyCertificate
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyCertificate
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyCertificate
     */
    companyId?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    authority?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    certificationDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    expiryDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    file?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyCertificate
     */
    url?: string | null;
}


