/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateProductionCommand
 */
export interface CreateProductionCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateProductionCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProductionCommand
     */
    productUid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductionCommand
     */
    startDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateProductionCommand
     */
    companyUid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProductionCommand
     */
    supplierUid?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProductionCommand
     */
    areaSize?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateProductionCommand
     */
    name?: string | null;
}


