/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CompanyType } from './company-type';

/**
 * 
 * @export
 * @interface CreateCompanyCommand
 */
export interface CreateCompanyCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    logo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCompanyCommand
     */
    sizeInSquareMeters?: number;
    /**
     * 
     * @type {CompanyType}
     * @memberof CreateCompanyCommand
     */
    companyType?: CompanyType;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    photo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    facebook?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    instagram?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    linkedin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    twitter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    youtube?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    producerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    producerTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    producerDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    producerEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    producerPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCompanyCommand
     */
    producerPhoto?: string | null;
}


