/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BatchDataItemModel } from './batch-data-item-model';

/**
 * 
 * @export
 * @interface CreateBatchDataCommand
 */
export interface CreateBatchDataCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateBatchDataCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBatchDataCommand
     */
    companyUid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBatchDataCommand
     */
    productionUid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateBatchDataCommand
     */
    batchUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBatchDataCommand
     */
    batchMetadataUid?: string;
    /**
     * 
     * @type {Array<BatchDataItemModel>}
     * @memberof CreateBatchDataCommand
     */
    items?: Array<BatchDataItemModel> | null;
}


