/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnvironmentDataType } from './environment-data-type';

/**
 * 
 * @export
 * @interface CreateEnvironmentDataCommand
 */
export interface CreateEnvironmentDataCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateEnvironmentDataCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {EnvironmentDataType}
     * @memberof CreateEnvironmentDataCommand
     */
    type?: EnvironmentDataType;
    /**
     * 
     * @type {string}
     * @memberof CreateEnvironmentDataCommand
     */
    companyUid?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEnvironmentDataCommand
     */
    productionUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateEnvironmentDataCommand
     */
    batchUid?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateEnvironmentDataCommand
     */
    value?: number;
}


