/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomizationPropertyFieldMappingModel } from './customization-property-field-mapping-model';

/**
 * 
 * @export
 * @interface CreateCustomizationCommand
 */
export interface CreateCustomizationCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomizationCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomizationCommand
     */
    companyUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomizationCommand
     */
    templateUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomizationCommand
     */
    productUid?: string | null;
    /**
     * 
     * @type {Array<CustomizationPropertyFieldMappingModel>}
     * @memberof CreateCustomizationCommand
     */
    mappings?: Array<CustomizationPropertyFieldMappingModel> | null;
}


