/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUserCommand
 */
export interface CreateUserCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    companyUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    companyName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateUserCommand
     */
    companyCode?: string | null;
}


