/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CredentialsModel
 */
export interface CredentialsModel {
    /**
     * 
     * @type {string}
     * @memberof CredentialsModel
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CredentialsModel
     */
    password?: string | null;
}


