/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomizationFieldType } from './customization-field-type';
import { CustomizationProperty } from './customization-property';

/**
 * 
 * @export
 * @interface CustomizationField
 */
export interface CustomizationField {
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomizationField
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomizationField
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof CustomizationField
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof CustomizationField
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationField
     */
    field?: string | null;
    /**
     * 
     * @type {CustomizationFieldType}
     * @memberof CustomizationField
     */
    type?: CustomizationFieldType;
    /**
     * 
     * @type {Array<CustomizationProperty>}
     * @memberof CustomizationField
     */
    properties?: Array<CustomizationProperty> | null;
    /**
     * 
     * @type {number}
     * @memberof CustomizationField
     */
    order?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomizationField
     */
    cardIndex?: number;
}


