/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomizationPropertyType } from './customization-property-type';

/**
 * 
 * @export
 * @interface CustomizationProperty
 */
export interface CustomizationProperty {
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomizationProperty
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomizationProperty
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof CustomizationProperty
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof CustomizationProperty
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    typeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    property?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    key?: string | null;
    /**
     * 
     * @type {CustomizationPropertyType}
     * @memberof CustomizationProperty
     */
    type?: CustomizationPropertyType;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    metadataProperties?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomizationProperty
     */
    metadataPropertyList?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CustomizationProperty
     */
    text?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CustomizationProperty
     */
    groupIndex?: number;
}


