/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomDataItem
 */
export interface CustomDataItem {
    /**
     * 
     * @type {string}
     * @memberof CustomDataItem
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDataItem
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomDataItem
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDataItem
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CustomDataItem
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomDataItem
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof CustomDataItem
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof CustomDataItem
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomDataItem
     */
    customDataId?: number;
    /**
     * 
     * @type {number}
     * @memberof CustomDataItem
     */
    customDataDefinitionItemId?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomDataItem
     */
    text?: string | null;
}


