/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EnvironmentDataType } from './environment-data-type';

/**
 * 
 * @export
 * @interface EnvironmentData
 */
export interface EnvironmentData {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentData
     */
    uid?: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentData
     */
    createdOn?: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentData
     */
    lastUpdatedOn?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EnvironmentData
     */
    isActive?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EnvironmentData
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentData
     */
    deletedOn?: string | null;
    /**
     * 
     * @type {Array<object>}
     * @memberof EnvironmentData
     */
    domainEvents?: Array<object> | null;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentData
     */
    id?: number;
    /**
     * 
     * @type {EnvironmentDataType}
     * @memberof EnvironmentData
     */
    type?: EnvironmentDataType;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentData
     */
    companyId?: number;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentData
     */
    productionId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentData
     */
    batchId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof EnvironmentData
     */
    value?: number;
}


