/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Company } from './company';

/**
 * 
 * @export
 * @interface ProductionModel
 */
export interface ProductionModel {
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    companyUid?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    supplierUid?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    startDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    productName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    productPhoto?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductionModel
     */
    areaSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    name?: string | null;
    /**
     * 
     * @type {Company}
     * @memberof ProductionModel
     */
    supplier?: Company;
    /**
     * 
     * @type {string}
     * @memberof ProductionModel
     */
    qrcodeUrl?: string | null;
}


