/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomizationField } from './customization-field';
import { CustomizationProperty } from './customization-property';

/**
 * 
 * @export
 * @interface QrCodeItem
 */
export interface QrCodeItem {
    /**
     * 
     * @type {CustomizationProperty}
     * @memberof QrCodeItem
     */
    property?: CustomizationProperty;
    /**
     * 
     * @type {CustomizationField}
     * @memberof QrCodeItem
     */
    field?: CustomizationField;
    /**
     * 
     * @type {any}
     * @memberof QrCodeItem
     */
    value?: any | null;
    /**
     * 
     * @type {string}
     * @memberof QrCodeItem
     */
    text?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof QrCodeItem
     */
    isActive?: boolean;
}


