/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCompanyContactCommand
 */
export interface UpdateCompanyContactCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    companyUid?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyContactCommand
     */
    avatar?: string | null;
}


