/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CustomDataItemModel } from './custom-data-item-model';

/**
 * 
 * @export
 * @interface UpdateCustomDataCommand
 */
export interface UpdateCustomDataCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomDataCommand
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomDataCommand
     */
    companyUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomDataCommand
     */
    productionUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomDataCommand
     */
    batchUid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomDataCommand
     */
    customDataDefinitionUId?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomDataCommand
     */
    text?: string | null;
    /**
     * 
     * @type {Array<CustomDataItemModel>}
     * @memberof UpdateCustomDataCommand
     */
    items?: Array<CustomDataItemModel> | null;
}


