/* tslint:disable */
/* eslint-disable */
/**
 * Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserModel
 */
export interface UserModel {
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    uid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    companyUid?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserModel
     */
    isSubscriber?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UserModel
     */
    availableProducts?: number;
    /**
     * 
     * @type {number}
     * @memberof UserModel
     */
    availableCustomers?: number;
    /**
     * 
     * @type {number}
     * @memberof UserModel
     */
    availableSuppliers?: number;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    subscriptionEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    subscriptionId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    customerId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserModel
     */
    isTrial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserModel
     */
    trialEndDate?: string | null;
}


